### PR TITLE
Fix crash when setting the savedir.

### PR DESCRIPTION
**Pull request by magical**

### CODE REVIEW

**Comment by magical** [comment]
Ping :)

**Comment by BR903** [comment]
My apologies for not responding to this at the time. After 4+ years I don't remember what caused me to lose track of this, but I'm looking at it now.

So, the if clause is determining whether or not to determine a value for `root`, which will be used to construct the default directory for the values being tested. But the save directory should not be underneath the default root, unlike the other three. That's why `save` is omitted from the if test. However, I see that it is in fact being used as a fallback, in the case when the user's home directory can't be determined. I'm not sure that that is the right choice -- but apparently it's been this way for over 15 years, so it would obviously be a bad idea to fiddle with it now.

Thanks for catching this, and for bringing it back to my attention.

**Comment by magical** [comment]
Ah, that makes sense. Presumably the fallback is there for the windows build, where the default root dir is `.` and the default save path is `./save`.

**Comment by BR903** [comment]
Yes, or really for any platform where there isn't a $HOME environment variable. (And of course nowadays I would handle this completely differently, as Windows now appears to have settled on using the $APPDATA environment variable for exactly this situation.)

**Pull request merged**
